name: Release

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - '**.md'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: App Authentication
        uses: actions/create-github-app-token@v1
        id: auth
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          repositories: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.auth.outputs.token }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: Set up Git
        run: |
          git config user.name 'release[bot]'
          git config user.email '${{ steps.auth.outputs.app-slug }}@github.com'

      - name: Commit bundle.js
        run: |
          git add -f dist/
          git commit -m 'chore(release): Added bundle.js [skip ci]'
          git push