name: Release

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: App Authentication
        uses: actions/create-github-app-token@v1
        id: auth
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}

      - name: Commit bundle.js
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          git config user.name 'relese[bot]'
          git config user.email '${{ steps.auth.outputs.app-slug }}@users.noreply.github.com'
          git remote remove origin
          # git remote add origin https://${{ secrets.MY_PAT }}@github.com/${{ github.repository }}.git
          git add package-lock.json
          git add -f dist/
          git commit -m 'chore(release): Added bundle.js [skip ci]'
          git push origin main