name: Release

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: App Authentication
        uses: actions/create-github-app-token@v1
        id: auth
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          repositories: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}

        
      - env:
          TT: ${{ steps.auth.outputs.token }}
        run: |
          git remote -v
          git remote remove origin
          git remote -v
          git remote add origin 'https://x-access-token:${{ env.TT }}@github.com/${{ github.repository }}.git'
          git remote -v

      - name: Commit bundle.js
        run: |
          git config user.name 'release[bot]'
          git config user.email '${{ steps.auth.outputs.app-slug }}@users.noreply.github.com'
          git add -f dist/
          git commit -m 'chore(release): Added bundle.js [skip ci]'
          git push origin main